# Generated by Django 5.1.7 on 2025-03-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_category_remove_contact_picture_contact_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="picture",
            field=models.ImageField(blank=True, upload_to="pictures/%Y/%m/"),
        ),
    ]
