# Generated by Django 5.1.7 on 2025-03-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_contact_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
